export const environment = {
    production: false,
    access_token: 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzNmQzMzRiYWEyOTU5NTQ4MzUyM2EwYjdiNjA5ZjFhMSIsInN1YiI6IjY0OWNjZDUxYzlkYmY5MDBhY2I5YjJkYSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.72HBsy_ra24c8nz7EnPK4tKyI7una4UUpxsa8ym-fr0'
}